version: '3'

services:

    ####################################################################################################
    # app
    ####################################################################################################
    app:
        container_name: whrongshock_app
        build: 
            context: .docker/php
            args:
                UID: ${UID:-1000}
                GID: ${GID:-1000}
        ports:
            - 5173:5173
            - 8002:8000
        volumes:
            - .:/var/www:cached
        networks:
            - whrongshock

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: whrongshock_nginx
        image: nginx
        ports:
            - 80:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - whrongshock

    ####################################################################################################
    # DATABASE (MySQL)
    ####################################################################################################
    db:
        container_name: whrongshock_mysql
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        env_file:
            - db.env
        networks:
            - whrongshock
    ####################################################################################################
    # Adminer
    ####################################################################################################
    adminer:
        container_name: whrongshock_adminer
        image: adminer
        ports:
            - "8080:8080"
        depends_on:
            - db
        networks:
            - whrongshock

networks:
  whrongshock:
    driver: bridge
    
    # ####################################################################################################
    # # DATABASE (MariaDB)
    # ####################################################################################################
    # db:
    #     container_name: laravel_mariadb
    #     image: mariadb:10.11
    #     ports:
    #         - 3306:3306
    #     volumes:
    #         - .docker/db/data:/var/lib/mysql
    #         - .docker/logs:/var/log/mysql
    #         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #         - .docker/db/sql:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #         MYSQL_DATABASE: laravel_db_name
    #         MYSQL_USER: laravel_db_user
    #         MYSQL_PASSWORD: laravel_db_pass

    ####################################################################################################
    # Mailpit
    ####################################################################################################
    # mail:
    #     container_name: fw_mailpit
    #     image: axllent/mailpit:latest
    #     ports:
    #     - 8025:8025
    #     - 1025:1025
    
    ####################################################################################################
    # phpMyAdmin
    ####################################################################################################
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     container_name: fw_phpmyadmin
    #     ports:
    #         - 8080:80
    #     links:
    #         - db
    #     environment:
    #         PMA_HOST: db
    #         PMA_PORT: 3306
    #         PMA_ARBITRARY: 1
    #     volumes:
    #         - .docker/phpmyadmin/sessions:/sessions
